// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"wire-tutorial/inmemory"
)

// Injectors from wire.go:

func initializeStorage(cfg Config) (*storageSet, func()) {
	string2 := cfg.Name
	storage, cleanup := inmemory.NewStorageWithNameAndClean(string2)
	int2, cleanup2 := provideCapacity(storage)
	storageName := provideName(storage)
	mainStorageSet := &storageSet{
		Storage:  storage,
		Capacity: int2,
		Name:     storageName,
	}
	return mainStorageSet, func() {
		cleanup2()
		cleanup()
	}
}

// wire.go:

type storageSet struct {
	Storage  KeyValueStorage
	Capacity int
	Name     StorageName
}

type StorageName string

func provideCapacity(ims *inmemory.Storage) (int, func()) {
	return ims.Len(), func() {
		println("capacity provider cleaner")
	}
}

func provideName(ims *inmemory.Storage) StorageName {
	return StorageName(ims.Name())
}
