// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"wire-tutorial/inmemory"
)

// Injectors from wire.go:

func initializeStorage(cfg Config) *storageSet {
	string2 := cfg.Name
	storage := inmemory.NewStorageWithName(string2)
	int2 := provideCapacity(storage)
	mainStorageSet := &storageSet{
		Storage:  storage,
		Capacity: int2,
	}
	return mainStorageSet
}

// wire.go:

type storageSet struct {
	Storage  KeyValueStorage
	Capacity int
}

func provideCapacity(ims *inmemory.Storage) int {
	return ims.Len()
}
