// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"wire-tutorial/inmemory"
)

// Injectors from wire.go:

func initializeStorage(cfg Config) KeyValueStorage {
	string2 := cfg.Name
	storage := inmemory.NewStorageWithName(string2)
	return storage
}
